name: main

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Publish plugin
        run: ./gradlew publishPlugins
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          gradlePublishKey: ${{ secrets.gradlePublishKey }}
          gradlePublishSecret: ${{ secrets.gradlePublishSecret }}